// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRest.Context;

namespace WebApiRest.Migrations
{
    [DbContext(typeof(dbSRICompElectContext))]
    [Migration("20220426003140_primera")]
    partial class primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiRest.Context.CasaComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CasacomercialId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CasacomercialDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CasacomercialEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CasacomercialEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CasacomercialNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CasacomercialPropietario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CasacomercialRuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CasacomercialTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CasaComercials");
                });

            modelBuilder.Entity("WebApiRest.Context.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClienteCiruc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebApiRest.Context.ComprobanteCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComprobantecId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CasacomercialId")
                        .HasColumnType("int");

                    b.Property<decimal>("ComprobantecDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComprobantecDetalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComprobantecEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ComprobantecFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComprobantecFormapago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ComprobantecIvatotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ComprobantecNumero")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComprobantecNumerocompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComprobantecNumerolocal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComprobantecNumeroserie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ComprobantecSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ComprobantecSubtotal0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ComprobantecSubtotal12")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComprobantecTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ComprobantecTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComprobanteCompras");
                });

            modelBuilder.Entity("WebApiRest.Context.ComprobanteVentum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComprobantevId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("ComprobantevDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComprobantevEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ComprobantevFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComprobantevFormapago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ComprobantevIvatotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComprobantevNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComprobantevRemision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ComprobantevSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ComprobantevSubtotal0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ComprobantevSubtotal12")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComprobantevTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ComprobantevTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Docsri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComprobanteVenta");
                });

            modelBuilder.Entity("WebApiRest.Context.DetalleVentum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetallevId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComprobantevId")
                        .HasColumnType("int");

                    b.Property<decimal>("DetallevCantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DetallevDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DetallevDescuentoporc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DetallevEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DetallevTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DetallevValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("WebApiRest.Context.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmpresaId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpresaActividadeconomica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaCalificacionartesanal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaClasecontribuyente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaNumerocalificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaOlc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaPropietario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaRuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("WebApiRest.Context.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocalId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("LocalActividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LocalFechainicioactividad")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locals");
                });

            modelBuilder.Entity("WebApiRest.Context.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ProductoCantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductoCod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductoFabricacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductoIva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductoValor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("WebApiRest.Context.Secuencial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecuencialId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FkEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("SecuencialNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecuencialTipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Secuencials");
                });

            modelBuilder.Entity("WebApiRest.Context.Tbdatosfacturacionelectronica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dfecontrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dfecontribuyente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dfeimagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Dfepruebaproduccion")
                        .HasColumnType("bit");

                    b.Property<string>("Dfeubicacionarchivop12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dfeubicacionruta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FkEmpresa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tbdatosfacturacionelectronicas");
                });

            modelBuilder.Entity("WebApiRest.Context.Tbdocumentosfacturacionelectronica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Empidfk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelectAmbiente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelectComprobantexml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelectEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelectFechaautorizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FelectIdentificador")
                        .HasColumnType("int");

                    b.Property<string>("FelectInformacionadicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelectMensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelectNumeroautorizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelectTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FkComprobanteVenta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tbdocumentosfacturacionelectronicas");
                });

            modelBuilder.Entity("WebApiRest.Context.TbrutasXml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FkComprobanteVenta")
                        .HasColumnType("int");

                    b.Property<string>("RutaAutorizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFirmado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaGenerado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaPdf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TbrutasXmls");
                });

            modelBuilder.Entity("WebApiRest.Context.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCodereset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioTipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
