// <auto-generated />
namespace AgricolaData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ARTABAN_00000011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ARTABAN_00000011));
        
        string IMigrationMetadata.Id
        {
            get { return "202206042328219_ARTABAN_00.000.011"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
